# A Basic bashrc for use with LINUX when the zshrc for Mac is not possible


# Set config directory
export XDG_CONFIG_HOME=~/.config

# Add z finder to terminal
. $HOME/workspace/z/z.sh
# Add krew bin to path. This is installed with scripts/k8s-krew, and is used for kubectl plugin management
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
