[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

eval "$(rbenv init -)"


# Install theme (needs to be brew installed)
fpath+=("$(brew --prefix)/share/zsh/site-functions")
autoload -U promptinit; promptinit
prompt pure

# Use z
. $(brew --prefix)/etc/profile.d/z.sh

# zsh's default history is very small, so we make it bigger
export SAVEHIST=100000 # Number of commands stored in history file
export HISTSIZE=50000
setopt INC_APPEND_HISTORY # append commands to file immediately, not on shell close
setopt HIST_IGNORE_ALL_DUPS # Don't write duplicate commands to history
setopt HIST_IGNORE_SPACE # Don't write commands that start with a space to history
 
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Set CLICOLOR if you want Ansi Colors in iTerm2
export CLICOLOR=1

# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color

export XDG_CONFIG_HOME=~/.config
# Aliases
alias vim="nvim"

# Path additions

# Add krew bin to path. This is installed with scripts/k8s-krew, and is used for kubectl plugin management
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/usr/local/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/usr/local/bin/google-cloud-sdk/completion.zsh.inc'; fi
