[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add homebrew to path
export PATH="/opt/homebrew/bin:$PATH"

# Install theme (needs to be brew installed)
fpath+=("$(brew --prefix)/share/zsh/site-functions")
autoload -U promptinit; promptinit

# Configure Pure prompt colors for high contrast
zstyle :prompt:pure:path color white
zstyle :prompt:pure:prompt:success color cyan
zstyle :prompt:pure:prompt:error color red
zstyle :prompt:pure:git:branch color yellow
zstyle :prompt:pure:git:dirty color magenta
zstyle :prompt:pure:git:stash show yes

prompt pure

# Use z
. $(brew --prefix)/etc/profile.d/z.sh

# zsh's default history is very small, so we make it bigger
export SAVEHIST=100000 # Number of commands stored in history file
export HISTSIZE=50000
setopt INC_APPEND_HISTORY # append commands to file immediately, not on shell close
setopt HIST_IGNORE_ALL_DUPS # Don't write duplicate commands to history
setopt HIST_IGNORE_SPACE # Don't write commands that start with a space to history
 
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Set CLICOLOR if you want Ansi Colors in iTerm2
export CLICOLOR=1

# Set high-contrast colors for ls output

# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color

export XDG_CONFIG_HOME=~/.config
# Aliases
alias vim="nvim"
alias glcoud="gcloud" #typo-proof


# Path additions
# Add krew bin to path. This is installed with scripts/k8s-krew, and is used for kubectl plugin management
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/usr/local/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/usr/local/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/usr/local/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/usr/local/bin/google-cloud-sdk/completion.zsh.inc'; fi
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

. "$HOME/.local/bin/env"
